/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Enquiry = {
  _id: string;
  _type: "enquiry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  projectType?:
    | "New website"
    | "Existing site update"
    | "Freelance enquiry"
    | "Job opportunity"
    | "Other";
  message?: string;
  status?: "New" | "Replied" | "Archived";
  submittedAt?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  email?: string;
  githubUrl?: string;
  linkedinUrl?: string;
  twitterUrl?: string;
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  location?: string;
  isOpenToWork?: boolean;
  resumeUrl?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?: "Language" | "Framework" | "Tool" | "Platform" | "Other";
  proficiency?: "Beginner" | "Intermediate" | "Advanced" | "Expert";
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  institution?: string;
  degree?: string;
  startYear?: number;
  endYear?: number;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SkillReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "skill";
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  role?: string;
  startDate?: string;
  endDate?: string;
  isCurrent?: boolean;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  skills?: Array<
    {
      _key: string;
    } & SkillReference
  >;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  authorName?: string;
  role?: string;
  company?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  quote?: string;
  date?: string;
  isFeatured?: boolean;
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
  >;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
  publishedAt?: string;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  techStack?: Array<
    {
      _key: string;
    } & SkillReference
  >;
  repoUrl?: string;
  liveUrl?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  isFeatured?: boolean;
  date?: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Enquiry
  | SiteSettings
  | SanityImageAssetReference
  | About
  | SanityImageCrop
  | SanityImageHotspot
  | Tag
  | Skill
  | Education
  | SkillReference
  | Experience
  | Testimonial
  | TagReference
  | Post
  | Slug
  | Project
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  email?: string;
  githubUrl?: string;
  linkedinUrl?: string;
  twitterUrl?: string;
  seoTitle?: string;
  seoDescription?: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0]{    headline,    bio,    avatar,    location,    isOpenToWork,    resumeUrl  }
export type ABOUT_QUERY_RESULT = {
  headline: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  avatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  location: string | null;
  isOpenToWork: boolean | null;
  resumeUrl: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(date desc){    _id,    title,    slug,    summary,    techStack[]->{ _id, name },    repoUrl,    liveUrl,    coverImage,    isFeatured,    date  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  techStack: Array<{
    _id: string;
    name: string | null;
  }> | null;
  repoUrl: string | null;
  liveUrl: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  isFeatured: boolean | null;
  date: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && isFeatured == true] | order(date desc){    _id,    title,    slug,    summary,    techStack[]->{ _id, name },    repoUrl,    liveUrl,    coverImage,    date  }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  techStack: Array<{
    _id: string;
    name: string | null;
  }> | null;
  repoUrl: string | null;
  liveUrl: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  date: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    title,    slug,    summary,    description,    techStack[]->{ _id, name },    repoUrl,    liveUrl,    coverImage,    date  }
export type PROJECT_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  techStack: Array<{
    _id: string;
    name: string | null;
  }> | null;
  repoUrl: string | null;
  liveUrl: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  date: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PAGINATED_PROJECTS_QUERY
// Query: *[_type == "project" && isFeatured != true] | order(date desc) [$start...$end]{    _id,    title,    slug,    summary,    techStack[]->{ _id, name },    repoUrl,    liveUrl,    coverImage,    isFeatured,    date  }
export type PAGINATED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  summary: string | null;
  techStack: Array<{
    _id: string;
    name: string | null;
  }> | null;
  repoUrl: string | null;
  liveUrl: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  isFeatured: boolean | null;
  date: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_COUNT_QUERY
// Query: count(*[_type == "project" && isFeatured != true])
export type PROJECTS_COUNT_QUERY_RESULT = number;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post"] | order(publishedAt desc){    _id,    title,    slug,    excerpt,    coverImage,    publishedAt,    tags[]->{ _id, name }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  publishedAt: string | null;
  tags: Array<{
    _id: string;
    name: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PAGINATED_POSTS_QUERY
// Query: *[_type == "post"] | order(publishedAt desc) [$start...$end]{    _id,    title,    slug,    excerpt,    coverImage,    publishedAt,    tags[]->{ _id, name }  }
export type PAGINATED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  publishedAt: string | null;
  tags: Array<{
    _id: string;
    name: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_COUNT_QUERY
// Query: count(*[_type == "post"])
export type POSTS_COUNT_QUERY_RESULT = number;

// Source: src/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    slug,    excerpt,    body,    coverImage,    publishedAt,    tags[]->{ _id, name }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  body: Array<
    | ({
        _key: string;
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  publishedAt: string | null;
  tags: Array<{
    _id: string;
    name: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"] | order(startDate desc){    _id,    company,    role,    startDate,    endDate,    isCurrent,    description,    logo,    skills[]->{ _id, name }  }
export type EXPERIENCE_QUERY_RESULT = Array<{
  _id: string;
  company: string | null;
  role: string | null;
  startDate: string | null;
  endDate: string | null;
  isCurrent: boolean | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  skills: Array<{
    _id: string;
    name: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: EDUCATION_QUERY
// Query: *[_type == "education"] | order(startYear desc){    _id,    institution,    degree,    startYear,    endYear,    description,    logo  }
export type EDUCATION_QUERY_RESULT = Array<{
  _id: string;
  institution: string | null;
  degree: string | null;
  startYear: number | null;
  endYear: number | null;
  description: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SKILLS_QUERY
// Query: *[_type == "skill"] | order(category asc, name asc){    _id,    name,    category,    proficiency  }
export type SKILLS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  category: "Framework" | "Language" | "Other" | "Platform" | "Tool" | null;
  proficiency: "Advanced" | "Beginner" | "Expert" | "Intermediate" | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(date desc){    _id,    authorName,    role,    company,    quote,    avatar,    date,    isFeatured  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  authorName: string | null;
  role: string | null;
  company: string | null;
  quote: string | null;
  avatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  date: string | null;
  isFeatured: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "about"][0]{\n    headline,\n    bio,\n    avatar,\n    location,\n    isOpenToWork,\n    resumeUrl\n  }\n': ABOUT_QUERY_RESULT;
    '\n  *[_type == "project"] | order(date desc){\n    _id,\n    title,\n    slug,\n    summary,\n    techStack[]->{ _id, name },\n    repoUrl,\n    liveUrl,\n    coverImage,\n    isFeatured,\n    date\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && isFeatured == true] | order(date desc){\n    _id,\n    title,\n    slug,\n    summary,\n    techStack[]->{ _id, name },\n    repoUrl,\n    liveUrl,\n    coverImage,\n    date\n  }\n': FEATURED_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    summary,\n    description,\n    techStack[]->{ _id, name },\n    repoUrl,\n    liveUrl,\n    coverImage,\n    date\n  }\n': PROJECT_QUERY_RESULT;
    '\n  *[_type == "project" && isFeatured != true] | order(date desc) [$start...$end]{\n    _id,\n    title,\n    slug,\n    summary,\n    techStack[]->{ _id, name },\n    repoUrl,\n    liveUrl,\n    coverImage,\n    isFeatured,\n    date\n  }\n': PAGINATED_PROJECTS_QUERY_RESULT;
    '\n  count(*[_type == "project" && isFeatured != true])\n': PROJECTS_COUNT_QUERY_RESULT;
    '\n  *[_type == "post"] | order(publishedAt desc){\n    _id,\n    title,\n    slug,\n    excerpt,\n    coverImage,\n    publishedAt,\n    tags[]->{ _id, name }\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post"] | order(publishedAt desc) [$start...$end]{\n    _id,\n    title,\n    slug,\n    excerpt,\n    coverImage,\n    publishedAt,\n    tags[]->{ _id, name }\n  }\n': PAGINATED_POSTS_QUERY_RESULT;
    '\n  count(*[_type == "post"])\n': POSTS_COUNT_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    excerpt,\n    body,\n    coverImage,\n    publishedAt,\n    tags[]->{ _id, name }\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "experience"] | order(startDate desc){\n    _id,\n    company,\n    role,\n    startDate,\n    endDate,\n    isCurrent,\n    description,\n    logo,\n    skills[]->{ _id, name }\n  }\n': EXPERIENCE_QUERY_RESULT;
    '\n  *[_type == "education"] | order(startYear desc){\n    _id,\n    institution,\n    degree,\n    startYear,\n    endYear,\n    description,\n    logo\n  }\n': EDUCATION_QUERY_RESULT;
    '\n  *[_type == "skill"] | order(category asc, name asc){\n    _id,\n    name,\n    category,\n    proficiency\n  }\n': SKILLS_QUERY_RESULT;
    '\n  *[_type == "testimonial"] | order(date desc){\n    _id,\n    authorName,\n    role,\n    company,\n    quote,\n    avatar,\n    date,\n    isFeatured\n  }\n': TESTIMONIALS_QUERY_RESULT;
  }
}
