/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: src/sanity/schema.json
export type Enquiry = {
  _id: string
  _type: 'enquiry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  email: string
  projectType?:
    | 'New website'
    | 'Existing site update'
    | 'Freelance enquiry'
    | 'Job opportunity'
    | 'Other'
  message: string
  status?: 'New' | 'Replied' | 'Archived'
  submittedAt?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  names: {
    first: string
    last: string
    display?: string
  }
  hero?: {
    heading: string
    tagline?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
  }
  favicon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  seo: {
    title: string
    description: string
  }
  email?: string
  phone?: string
  hasWhatsApp?: boolean
  socialUrls?: {
    github?: string
    linkedin?: string
    twitter?: string
    stackoverflow?: string
  }
  cv?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type About = {
  _id: string
  _type: 'about'
  _createdAt: string
  _updatedAt: string
  _rev: string
  headline: string
  bio: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  avatar: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  location: string
  isOpenToWork: boolean
}

export type Tag = {
  _id: string
  _type: 'tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
}

export type Skill = {
  _id: string
  _type: 'skill'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  category?: 'Language' | 'Framework' | 'Tool' | 'Platform' | 'Other'
  proficiency?: 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert'
}

export type Education = {
  _id: string
  _type: 'education'
  _createdAt: string
  _updatedAt: string
  _rev: string
  institution: {
    name: string
    type: 'secondary' | 'sixthForm' | 'university' | 'other'
    logo?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    location?: string
    url?: string
  }
  qualification: string
  fieldOfStudy?: string
  grade?: string
  startYear: number
  isCurrent?: boolean
  endYear?: number
  description: string
  highlights?: Array<string>
}

export type SkillReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'skill'
}

export type Experience = {
  _id: string
  _type: 'experience'
  _createdAt: string
  _updatedAt: string
  _rev: string
  company: {
    name: string
    logo?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    website?: string
  }
  employment: {
    startDate: string
    isCurrent?: boolean
    endDate?: string
    location: string
  }
  role: {
    title: string
    summary: string
    highlights: Array<string>
    impact: string
  }
  skills: Array<
    {
      _key: string
    } & SkillReference
  >
  slug: Slug
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  author: {
    name: string
    avatar?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    role: string
    company: string
  }
  quote: string
  isFeatured?: boolean
}

export type TagReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'tag'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  excerpt?: string
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & Code)
  >
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  featured?: boolean
  tags?: Array<
    {
      _key: string
    } & TagReference
  >
  publishedAt?: string
  updatedAt?: string
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  category:
    'Full Stack' | 'Frontend' | 'Backend' | 'UI/UX' | 'Open Source' | 'Client Work'
  content: {
    summary: string
    problem?: string
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    technologies: Array<
      {
        _key: string
      } & SkillReference
    >
    features: Array<string>
    challenges?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
  }
  urls: {
    repo?: string
    live?: string
  }
  media: {
    coverImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    screenshots?: Array<{
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }>
  }
  isFeatured?: boolean
  date: string
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Enquiry
  | SanityImageAssetReference
  | SanityFileAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | About
  | Tag
  | Skill
  | Education
  | SkillReference
  | Experience
  | Slug
  | Testimonial
  | TagReference
  | Post
  | Project
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    ..., // spreads all existing fields    names{      ...,      "full": first + " " + last    },    'ogImage': *[_type == "about"][0].avatar,    favicon{      asset->{        _id,        url      }    },    cv{      asset->{        _id,        url,        originalFilename,        size      }    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  names: {
    first: string
    last: string
    display?: string
    full: string
  }
  hero?: {
    heading: string
    tagline?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
  }
  favicon: {
    asset: {
      _id: string
      url: string
    } | null
  } | null
  seo: {
    title: string
    description: string
  }
  email?: string
  phone?: string
  hasWhatsApp?: boolean
  socialUrls?: {
    github?: string
    linkedin?: string
    twitter?: string
    stackoverflow?: string
  }
  cv: {
    asset: {
      _id: string
      url: string
      originalFilename: string | null
      size: number
    } | null
  } | null
  ogImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  } | null
} | null

// Source: src/sanity/lib/queries.ts
// Variable: USER_NAMES_QUERY
// Query: *[_type == "siteSettings"][0].names{      ...,      "full": first + " " + last    }
export type USER_NAMES_QUERY_RESULT = {
  first: string
  last: string
  display?: string
  full: string
} | null

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0] {    ...,    "cv": *[_type == "siteSettings"][0].cv  }
export type ABOUT_QUERY_RESULT = {
  _id: string
  _type: 'about'
  _createdAt: string
  _updatedAt: string
  _rev: string
  headline: string
  bio: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  avatar: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  location: string
  isOpenToWork: boolean
  cv: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  } | null
} | null

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(date desc){    _id,    title,    'slug': slug.current,    category,    content{      summary,      problem,      description,      "technologies": coalesce(technologies[]->{ _id, name }, []),      features,      challenges    },    urls{      repo,      live    },    media{      coverImage,      "screenshots": coalesce(screenshots, []),    },    isFeatured,    date  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
  category:
    'Backend' | 'Client Work' | 'Frontend' | 'Full Stack' | 'Open Source' | 'UI/UX'
  content: {
    summary: string
    problem: string | null
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    technologies: Array<{
      _id: string
      name: string
    }>
    features: Array<string>
    challenges: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
  }
  urls: {
    repo: string | null
    live: string | null
  }
  media: {
    coverImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    screenshots:
      | Array<{
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }>
      | Array<never>
  }
  isFeatured: boolean | null
  date: string
}>

// Source: src/sanity/lib/queries.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && isFeatured == true] | order(date desc){    _id,    title,    'slug': slug.current,    category,    content{      summary,      problem,      description,      "technologies": coalesce(technologies[]->{ _id, name }, []),      features,      challenges    },    urls{      repo,      live    },    media{      coverImage,      "screenshots": coalesce(screenshots, []),    },    date  }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
  category:
    'Backend' | 'Client Work' | 'Frontend' | 'Full Stack' | 'Open Source' | 'UI/UX'
  content: {
    summary: string
    problem: string | null
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    technologies: Array<{
      _id: string
      name: string
    }>
    features: Array<string>
    challenges: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
  }
  urls: {
    repo: string | null
    live: string | null
  }
  media: {
    coverImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    screenshots:
      | Array<{
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }>
      | Array<never>
  }
  date: string
}>

// Source: src/sanity/lib/queries.ts
// Variable: FEATURED_PROJECTS_CARDS_QUERY
// Query: *[_type == "post" && isFeatured == true] | order(date desc){    _id,    'slug': slug.current,    title,    category,    media{      coverImage    },    content{      summary,      "technologies": technologies[]->{ _id, name }    },    date  }
export type FEATURED_PROJECTS_CARDS_QUERY_RESULT = Array<never>

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    title,    'slug': slug.current,    category,    content{      summary,      problem,      description,      "technologies": coalesce(technologies[]->{ _id, name }, []),      features,      challenges    },    urls{      repo,      live    },    media{      coverImage,      "screenshots": coalesce(screenshots, []),    },    date  }
export type PROJECT_QUERY_RESULT = {
  _id: string
  title: string
  slug: string
  category:
    'Backend' | 'Client Work' | 'Frontend' | 'Full Stack' | 'Open Source' | 'UI/UX'
  content: {
    summary: string
    problem: string | null
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    technologies: Array<{
      _id: string
      name: string
    }>
    features: Array<string>
    challenges: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
  }
  urls: {
    repo: string | null
    live: string | null
  }
  media: {
    coverImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    screenshots:
      | Array<{
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }>
      | Array<never>
  }
  date: string
} | null

// Source: src/sanity/lib/queries.ts
// Variable: PAGINATED_PROJECTS_QUERY
// Query: *[_type == "project" && isFeatured != true] | order(date desc) [$start...$end]{    _id,    title,    'slug': slug.current,    category,    content{      summary,      problem,      description,      "technologies": coalesce(technologies[]->{ _id, name }, []),      features,      challenges    },    urls{      repo,      live    },    media{      coverImage,      "screenshots": coalesce(screenshots, []),    },    isFeatured,    date  }
export type PAGINATED_PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
  category:
    'Backend' | 'Client Work' | 'Frontend' | 'Full Stack' | 'Open Source' | 'UI/UX'
  content: {
    summary: string
    problem: string | null
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    technologies: Array<{
      _id: string
      name: string
    }>
    features: Array<string>
    challenges: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
  }
  urls: {
    repo: string | null
    live: string | null
  }
  media: {
    coverImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    screenshots:
      | Array<{
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }>
      | Array<never>
  }
  isFeatured: boolean | null
  date: string
}>

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_COUNT_QUERY
// Query: count(*[_type == "project" && isFeatured != true])
export type PROJECTS_COUNT_QUERY_RESULT = number

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post"] | order(publishedAt desc){    _id,    title,    'slug': slug.current,    excerpt,    coverImage,    tags[]->{ _id, name }, // 📚 Take the tags array and iterate over it. -> means resolve each reference i.e. join the related document using the reference (_ref) it holds    publishedAt,    updatedAt  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  tags: Array<{
    _id: string
    name: string
  }> | null
  publishedAt: string | null
  updatedAt: string | null
}>

// Source: src/sanity/lib/queries.ts
// Variable: PAGINATED_POSTS_QUERY
// Query: *[_type == "post"] | order(publishedAt desc) [$start...$end]{    _id,    title,    'slug': slug.current,    excerpt,    coverImage,    tags[]->{ _id, name },    publishedAt,    updatedAt  }
export type PAGINATED_POSTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  tags: Array<{
    _id: string
    name: string
  }> | null
  publishedAt: string | null
  updatedAt: string | null
}>

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_COUNT_QUERY
// Query: count(*[_type == "post"])
export type POSTS_COUNT_QUERY_RESULT = number

// Source: src/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    'slug': slug.current,    excerpt,    body,    coverImage,    "tags": coalesce(tags[]->{ _id, name }, []),    publishedAt,    updatedAt  }
export type POST_QUERY_RESULT = {
  _id: string
  title: string
  slug: string
  excerpt: string | null
  body: Array<
    | ({
        _key: string
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  tags:
    | Array<{
        _id: string
        name: string
      }>
    | Array<never>
  publishedAt: string | null
  updatedAt: string | null
} | null

// Source: src/sanity/lib/queries.ts
// Variable: EXPERIENCES_QUERY
// Query: *[_type == "experience"] | order(employment.startDate desc) {    _id,    _type,    _createdAt,    _updatedAt,    _rev,    company {      name,      logo,      website    },    employment {      startDate,      isCurrent,      endDate,      location    },    role {      title,      summary,      "highlights": coalesce(highlights, []), // coalesce says, the result is null, return an empty array instead (good for frontend DX)      impact    },    "skills": coalesce(skills[]->{ _id, name }, []),     slug  }
export type EXPERIENCES_QUERY_RESULT = Array<{
  _id: string
  _type: 'experience'
  _createdAt: string
  _updatedAt: string
  _rev: string
  company: {
    name: string
    logo: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    website: string | null
  }
  employment: {
    startDate: string
    isCurrent: boolean | null
    endDate: string | null
    location: string
  }
  role: {
    title: string
    summary: string
    highlights: Array<string>
    impact: string
  }
  skills: Array<{
    _id: string
    name: string
  }>
  slug: Slug
}>

// Source: src/sanity/lib/queries.ts
// Variable: EDUCATIONS_QUERY
// Query: *[_type == "education"] | order(startYear desc){    ...,    "highlights": coalesce(highlights, [])  }
export type EDUCATIONS_QUERY_RESULT = Array<{
  _id: string
  _type: 'education'
  _createdAt: string
  _updatedAt: string
  _rev: string
  institution: {
    name: string
    type: 'other' | 'secondary' | 'sixthForm' | 'university'
    logo?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    location?: string
    url?: string
  }
  qualification: string
  fieldOfStudy?: string
  grade?: string
  startYear: number
  isCurrent?: boolean
  endYear?: number
  description: string
  highlights: Array<string> | Array<never>
}>

// Source: src/sanity/lib/queries.ts
// Variable: CV_QUERY
// Query: *[_type == "siteSettings"][0].cv{    asset->{      _id,      url,      originalFilename,      size    }  }
export type CV_QUERY_RESULT = {
  asset: {
    _id: string
    url: string
    originalFilename: string | null
    size: number
  } | null
} | null

// Source: src/sanity/lib/queries.ts
// Variable: SKILLS_QUERY
// Query: *[_type == "skill"] | order(category asc, name asc)
export type SKILLS_QUERY_RESULT = Array<{
  _id: string
  _type: 'skill'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  category?: 'Framework' | 'Language' | 'Other' | 'Platform' | 'Tool'
  proficiency?: 'Advanced' | 'Beginner' | 'Expert' | 'Intermediate'
}>

// Source: src/sanity/lib/queries.ts
// Variable: TECH_SKILLS_QUERY
// Query: *[_type == "skill" && category != "Other"] | order(category asc, name asc)
export type TECH_SKILLS_QUERY_RESULT = Array<{
  _id: string
  _type: 'skill'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  category?: 'Framework' | 'Language' | 'Other' | 'Platform' | 'Tool'
  proficiency?: 'Advanced' | 'Beginner' | 'Expert' | 'Intermediate'
}>

// Source: src/sanity/lib/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(date desc)
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  author: {
    name: string
    avatar?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    role: string
    company: string
  }
  quote: string
  isFeatured?: boolean
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    ..., // spreads all existing fields\n    names{\n      ...,\n      "full": first + " " + last\n    },\n    \'ogImage\': *[_type == "about"][0].avatar,\n    favicon{\n      asset->{\n        _id,\n        url\n      }\n    },\n    cv{\n      asset->{\n        _id,\n        url,\n        originalFilename,\n        size\n      }\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT
    '\n  *[_type == "siteSettings"][0].names{\n      ...,\n      "full": first + " " + last\n    }\n': USER_NAMES_QUERY_RESULT
    '\n  *[_type == "about"][0] {\n    ...,\n    "cv": *[_type == "siteSettings"][0].cv\n  }\n': ABOUT_QUERY_RESULT
    '\n  *[_type == "project"] | order(date desc){\n    _id,\n    title,\n    \'slug\': slug.current,\n    category,\n    content{\n      summary,\n      problem,\n      description,\n      "technologies": coalesce(technologies[]->{ _id, name }, []),\n      features,\n      challenges\n    },\n    urls{\n      repo,\n      live\n    },\n    media{\n      coverImage,\n      "screenshots": coalesce(screenshots, []),\n    },\n    isFeatured,\n    date\n  }\n': PROJECTS_QUERY_RESULT
    '\n  *[_type == "project" && isFeatured == true] | order(date desc){\n    _id,\n    title,\n    \'slug\': slug.current,\n    category,\n    content{\n      summary,\n      problem,\n      description,\n      "technologies": coalesce(technologies[]->{ _id, name }, []),\n      features,\n      challenges\n    },\n    urls{\n      repo,\n      live\n    },\n    media{\n      coverImage,\n      "screenshots": coalesce(screenshots, []),\n    },\n    date\n  }\n': FEATURED_PROJECTS_QUERY_RESULT
    '\n  *[_type == "post" && isFeatured == true] | order(date desc){\n    _id,\n    \'slug\': slug.current,\n    title,\n    category,\n    media{\n      coverImage\n    },\n    content{\n      summary,\n      "technologies": technologies[]->{ _id, name }\n    },\n    date\n  }\n  ': FEATURED_PROJECTS_CARDS_QUERY_RESULT
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    _id,\n    title,\n    \'slug\': slug.current,\n    category,\n    content{\n      summary,\n      problem,\n      description,\n      "technologies": coalesce(technologies[]->{ _id, name }, []),\n      features,\n      challenges\n    },\n    urls{\n      repo,\n      live\n    },\n    media{\n      coverImage,\n      "screenshots": coalesce(screenshots, []),\n    },\n    date\n  }\n': PROJECT_QUERY_RESULT
    '\n  *[_type == "project" && isFeatured != true] | order(date desc) [$start...$end]{\n    _id,\n    title,\n    \'slug\': slug.current,\n    category,\n    content{\n      summary,\n      problem,\n      description,\n      "technologies": coalesce(technologies[]->{ _id, name }, []),\n      features,\n      challenges\n    },\n    urls{\n      repo,\n      live\n    },\n    media{\n      coverImage,\n      "screenshots": coalesce(screenshots, []),\n    },\n    isFeatured,\n    date\n  }\n': PAGINATED_PROJECTS_QUERY_RESULT
    '\n  count(*[_type == "project" && isFeatured != true])\n': PROJECTS_COUNT_QUERY_RESULT
    '\n  *[_type == "post"] | order(publishedAt desc){\n    _id,\n    title,\n    \'slug\': slug.current,\n    excerpt,\n    coverImage,\n    tags[]->{ _id, name }, // \uD83D\uDCDA Take the tags array and iterate over it. -> means resolve each reference i.e. join the related document using the reference (_ref) it holds\n    publishedAt,\n    updatedAt\n  }\n': POSTS_QUERY_RESULT
    '\n  *[_type == "post"] | order(publishedAt desc) [$start...$end]{\n    _id,\n    title,\n    \'slug\': slug.current,\n    excerpt,\n    coverImage,\n    tags[]->{ _id, name },\n    publishedAt,\n    updatedAt\n  }\n': PAGINATED_POSTS_QUERY_RESULT
    '\n  count(*[_type == "post"])\n': POSTS_COUNT_QUERY_RESULT
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    \'slug\': slug.current,\n    excerpt,\n    body,\n    coverImage,\n    "tags": coalesce(tags[]->{ _id, name }, []),\n    publishedAt,\n    updatedAt\n  }\n': POST_QUERY_RESULT
    '\n    *[_type == "experience"] | order(employment.startDate desc) {\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n\n    company {\n      name,\n      logo,\n      website\n    },\n\n    employment {\n      startDate,\n      isCurrent,\n      endDate,\n      location\n    },\n\n    role {\n      title,\n      summary,\n      "highlights": coalesce(highlights, []), // coalesce says, the result is null, return an empty array instead (good for frontend DX)\n      impact\n    },\n\n    "skills": coalesce(skills[]->{ _id, name }, []), \n\n    slug\n  }\n': EXPERIENCES_QUERY_RESULT
    '\n  *[_type == "education"] | order(startYear desc){\n    ...,\n    "highlights": coalesce(highlights, [])\n  }\n': EDUCATIONS_QUERY_RESULT
    '\n  *[_type == "siteSettings"][0].cv{\n    asset->{\n      _id,\n      url,\n      originalFilename,\n      size\n    }\n  }\n': CV_QUERY_RESULT
    '\n  *[_type == "skill"] | order(category asc, name asc)\n': SKILLS_QUERY_RESULT
    '\n  *[_type == "skill" && category != "Other"] | order(category asc, name asc)\n': TECH_SKILLS_QUERY_RESULT
    '\n  *[_type == "testimonial"] | order(date desc)\n': TESTIMONIALS_QUERY_RESULT
  }
}
